#!/bin/sh

\rm -f usno_finals.erp
wget https://vlbi.gsfc.nasa.gov/apriori/usno500_finals.erp && \mv -f usno_finals.erp .eops
\rm -f ut1ls.dat
wget https://vlbi.gsfc.nasa.gov/apriori/ut1ls.dat && \mv -f ut1ls.dat .ut1ls



