#!/bin/sh
\rm -f usno500_finals.erp
wget ftp://ftp.lbo.us/pub/staff/wbrisken/EOP/usno500_finals.erp && \mv -f usno500_finals.erp .eops
#\rm -f usno500_finals.erp
#wget https://vlbi.gsfc.nasa.gov/apriori/usno500_finals.erp && \mv -f usno500_finals.erp .eops
#\rm -f ut1ls.dat
#wget https://vlbi.gsfc.nasa.gov/apriori/ut1ls.dat && \mv -f ut1ls.dat .ut1ls



