      SUBROUTINE CKILL ( LNAME, I1, I2 )
      IMPLICIT None
C 
C 1.     KILL 
C 
C 1.1    KILL PROGRAM SPECIFICATION 
C 
C 1.1.1  KILL IS THE UTILITY ROUTINE WHICH TERMINATES THE CALC PROGRAM IF A 
C        DATA BASE INTERFACE ERROR IS DETECTED IN THE PROGRAM. 
C 
C 1.2    KILL PROGRAM INTERFACE 
C 
C 1.2.1  CALLING SEQUENCE - 
C 
C        INPUT VARIABLES: 
C          1. I1       -  THE NUMBER OF THE DATA BASE INTERFACE ERROR FLAG WHICH
C                         CAUSED THE KILL. 
C          2. I2       -  THE VALUE RETURNED BY THE DATA BASE ERROR RETURN FLAG.
C          3. LNAME(3) -  THE NAME OF THE SUBROUTINE IN WHICH THE PROGRAM
C                         TERMINATED. 
C 
C 1.2.2 COMMON BLOCKS USED - CON
C 
      INCLUDE 'ccon.i'             
C 
C 1.2.3  PROGRAM SPECIFICATIONS -
C
      INTEGER*2  LNAME(3),IPAR(5), I1, I2
      CHARACTER*10 IPAR_C
      EQUIVALENCE (IPAR,IPAR_C)
C
C 1.2.4  DATA BASE ACCESS -  NONE
C
C 1.2.5  EXTERNAL INPUT/OUTPUT -
C               INPUT VARIABLES:  NONE
C               OUTPUT VARIABLES: THE PROGRAM TERMINATION MESSAGE
C
C 1.2.6  SUBROUTINE INTERFACE -
C              CALLER SUBROUTINES: ALL ROUTINES WITH DATA BASE INTERFACES.
C              CALLED SUBROUTINES: NONE
C
C 1.2.7  CONSTANTS USED - NONE
C
C 1.2.8  PROGRAM VARIABLES -   NONE
C
C 1.2.9  PROGRAMMER - DALE MARKHAM  01/20/77
C                     PETER DENATALE 07/18/77
C                     BRUCE SCHUPLER 01/11/80
C                     SAVITA GOEL    06/04/87 (CDS FOR A900)
C                     Jim Ryan 90.01.26  QUIT_CALC implemented.
C                     David Gordon 94.04.12 Edit termination message for Calc 8.
C                     David Gordon 94.04.14 Change to Implicit none.
C
C 1.3    KILL PROGRAM STRUCTURE
C
C    WRITE OUT THE MESSAGE WHICH INDICATES THE PROGRAM HAS BEEN KILLED.
      WRITE( 7, 9000 ) LNAME, I1, I2
 9000 FORMAT (1X, "CALC has terminated in subroutine ", 3A2,
     1        ',', 'KERR(', I1, ') = ', I2, '.' )
C
C   CLEANUP THE DATA BASE HANDLER
      CALL FINIS(1)
C
C   TERMINATE THE PROGRAM.
      IPAR_C = 'CALC Fail '
      CALL QUIT_CALC(IPAR)
      END
