.PHONY : all clean install

//TARGETS := difx_monitor monitor_server mon_sample difx_config vcal
TARGETS :=  monitor_server mon_sample difx_config vcal

all    : $(TARGETS)

clean  : $(TARGETS)
	rm -f *.o $^

install: $(TARGETS)
	cp $(TARGETS) stripinput.pl $(DIFXROOT)/bin

CXX = $(MPICXX) -g -Wall
#CPPFLAGS = -O2 -D__PWD=\"$$PWD\"
CPPFLAGS =  -D__PWD=\"$$PWD\"
F77 = g77

INCS = -I$(DIFXROOT)/include/ -I$(IPPROOT)/include 
LIBS =  -L$(DIFXROOT)/lib/ -L$(IPPROOT)/Libraries -lmpifxcorr -lmark5access -ldifxmessage $(IPPLINKLIBS) 
PGPLOTLIBS = -lcpgplot -lpgplot 

difx_monitor : difx_monitor.cpp monserver.cpp monserver.h
	$(CXX) $(CPPFLAGS) $(INCS) -o $@ $^ $(LIBS) $(PGPLOTLIBS)

vcal : vcal.cpp monserver.cpp monserver.h
	$(CXX) $(CPPFLAGS) $(INCS) -o $@ $^ $(LIBS) 

difx_config : difx_config.cpp 
	$(CXX) $(CPPFLAGS) $(INCS) -o $@ $^ $(LIBS) 

monitor_server : monitor_server.cpp monserver.cpp monserver.h
	$(CXX) $(CPPFLAGS) $(INCS) -o $@ $^ $(LIBS) 

mon_sample: mon_sample.cpp monserver.cpp monserver.h
	$(CXX) $(CPPFLAGS) $(INCS) -o $@  $^ $(LIBS) $(PGPLOTLIBS)

mon3d: mon3d.c monserver.cpp
	$(CXX) $(CPPFLAGS) $(INCS) -o $@  $^ $(LIBS)
