#include <stdio.h>
#include <string.h>
#include <math.h>
#include <ctype.h>
#include <fcntl.h>
#include <rpc/rpc.h>
#include <glob.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include "config.h"
#include "difxcalc.h"
#include "CALCServer.h"

#define MAX_FILES	2048

const char program[] = "calcif2";
const char author[]  = "Walter Brisken <wbrisken@nrao.edu>";
const char version[] = "0.1";
const char verdate[] = "20080703";

typedef struct
{
	int verbose;
	int force;
	int doall;
	char calcServer[32];
	int calcProgram;
	int calcVersion;
	int nFile;
	char *files[MAX_FILES];
} CommandLineOptions;

int usage()
{
	fprintf(stderr, "%s ver. %s  %s  %s\n\n", program, version, 
		author, verdate);
	fprintf(stderr, "A program to calculate a model for DiFX using a calc "
		"server.\n\n");
	fprintf(stderr, "Usage : %s [options] { <input file> | -a }\n\n", 
		program);
	fprintf(stderr, "<calc file> should be a '.calc' file as generated by "
		"job2difx.\n\n");
	fprintf(stderr, "options can include:\n");
	fprintf(stderr, "  --help\n");
	fprintf(stderr, "  -h                      Print this help and quit\n");
	fprintf(stderr, "\n");
	fprintf(stderr, "  --verbose\n");
	fprintf(stderr, "  -v                      Be more verbose in operation\n");
	fprintf(stderr, "\n");
	fprintf(stderr, "  --force\n");
	fprintf(stderr, "  -f                      Force recalc\n");
	fprintf(stderr, "\n");
	fprintf(stderr, "  --all\n");
	fprintf(stderr, "  -a                      Do all calc files found\n");
	fprintf(stderr, "\n");
	fprintf(stderr, "  --server <servername>\n");
	fprintf(stderr, "  -s       <servername>   Use <servername> as calcserver\n\n");
	fprintf(stderr, "      By default 'localhost' will be the calcserver.  An "
		"environment\n");
	fprintf(stderr, "      variable CALC_SERVER can be used to override that.  The "
		"command line\n");
	fprintf(stderr, "      overrides all.\n");
	fprintf(stderr, "\n");
	return 0;
}

void deleteCommandLineOptions(CommandLineOptions *opts)
{
	int i;

	if(!opts)
	{
		return;
	}

	for(i = 0; i < opts->nFile; i++)
	{
		free(opts->files[i]);
	}

	free(opts);
}

CommandLineOptions *newCommandLineOptions(int argc, char **argv)
{
	CommandLineOptions *opts;
	glob_t globbuf;
	int i;
	char *cs;

	opts = (CommandLineOptions *)calloc(1, sizeof(CommandLineOptions));

	for(i = 1; i < argc; i++)
	{
		if(argv[i][0] == '-')
		{
			if(strcmp(argv[i], "-v") == 0 ||
			   strcmp(argv[i], "--verbose") == 0)
			{
				opts->verbose++;
			}
			else if(strcmp(argv[i], "-f") == 0 ||
				strcmp(argv[i], "--force") == 0)
			{
				opts->force++;
			}
			else if(strcmp(argv[i], "-a") == 0 ||
			        strcmp(argv[i], "--all") == 0)
			{
				opts->doall = 1;
			}
			else if(strcmp(argv[i], "-h") == 0 ||
				strcmp(argv[i], "--help") == 0)
			{
				usage();
				deleteCommandLineOptions(opts);
				return 0;
			}
			else if(argv[i][0] == '-')
			{
				printf("Illegal option : %s\n", argv[i]);
				deleteCommandLineOptions(opts);
				return 0;
			}
			else if(i+1 < argc)
			{
				if(strcmp(argv[i], "--server") == 0 ||
				   strcmp(argv[i], "-s") == 0)
				{
					i++;
					strncpy(opts->calcServer, argv[i], 31);
					opts->calcServer[31] = 0;
				}

			}
		}
		else
		{
			opts->files[opts->nFile] = strdup(argv[i]);
			opts->nFile++;
			if(opts->nFile >= MAX_FILES)
			{
				fprintf(stderr, "Too many files (%d max)\n", 
					MAX_FILES);
				deleteCommandLineOptions(opts);
				return 0;
			}
		}
	}

	if(opts->doall == 0 && opts->nFile == 0)
	{
		fprintf(stderr, "No input files!  Quitting.\n");
		deleteCommandLineOptions(opts);
		return 0;
	}

	if(opts->doall > 0)
	{
		if(opts->nFile > 0)
		{
			fprintf(stderr, "--all and files!  Quitting.\n");
			deleteCommandLineOptions(opts);
			return 0;
		}
		glob("*.calc", 0, 0, &globbuf);
		opts->nFile = globbuf.gl_pathc;
		if(opts->nFile >= MAX_FILES)
		{
			fprintf(stderr, "Too many files (%d max)\n", MAX_FILES);
			deleteCommandLineOptions(opts);
			return 0;
		}
		if(opts->nFile <= 0)
		{
			fprintf(stderr, "No .calc files found.  Quitting.\n");
			fprintf(stderr, "Hint: Did you run job2difx yet???\n");
			deleteCommandLineOptions(opts);
			return 0;
		}
		for(i = 0; i < opts->nFile; i++)
		{
			opts->files[i] = strdup(globbuf.gl_pathv[i]);
		}
		globfree(&globbuf);
	}

	if(opts->calcServer[0] == 0)
	{
		cs = getenv("CALC_SERVER");
		if(cs)
		{
			strncpy(opts->calcServer, cs, 31);
			opts->calcServer[31] = 0;
		}
		else
		{
			strcpy(opts->calcServer, "localhost");
		}
	}

	opts->calcVersion = CALCVERS;
	opts->calcProgram = CALCPROG;

	return opts;
}

int runfile(const char *prefix, const CommandLineOptions *opts,
	CalcParams *p)
{
	DifxInput *D;
	int v;

	D = loadDifxCalc(prefix);
	D = updateDifxInput(D);
	
	if(D)
	{
		strncpy(D->job->calcServer, opts->calcServer, 31);
		D->job->calcServer[31] = 0;
		D->job->calcProgram = opts->calcProgram;
		D->job->calcVersion = opts->calcVersion;

		if(opts->verbose > 1)
		{
			printDifxInput(D);
		}

		v = difxCalcInit(D, p);
		if(v < 0)
		{
			deleteDifxInput(D);
			printf("difxCalcInit returned %d\n", v);
			return -1;
		}
		v = difxCalc(D, p);
		if(v < 0)
		{
			deleteDifxInput(D);
			printf("difxCalc returned %d\n", v);
			return -1;
		}

		writeDifxDelay(D, "delay");
//		writeDifxRate(D, "rate");
		writeDifxUVW(D, "uvw");
		writeDifxIM(D, "im");

		deleteDifxInput(D);

		return 0;
	}
	else
	{
		return -1;
	}
}

void deleteCalcParams(CalcParams *p)
{
	free(p);
}

CalcParams *newCalcParams(const CommandLineOptions *opts)
{
	CalcParams *p;

	p = (CalcParams *)calloc(1, sizeof(CalcParams));

	p->increment = 120;
	p->order = 5;

	p->delta = 0.0001;

	strncpy(p->calcServer, opts->calcServer, 31);
	p->calcServer[31] = 0;
	p->calcProgram = opts->calcProgram;
	p->calcVersion = opts->calcVersion;

	p->clnt = clnt_create(p->calcServer, p->calcProgram, p->calcVersion, 
		"tcp");
	if(!p->clnt)
	{
		clnt_pcreateerror(p->calcServer);
		printf("ERROR: rpc clnt_create fails for host : %-s\n",
			p->calcServer);
		deleteCalcParams(p);
		return 0;
	}
	if(opts->verbose > 1)
	{
		printf("RPC client created\n");
	}

	return p;
}

int run(const CommandLineOptions *opts)
{
	CalcParams *p;
	int i, l;

	if(opts == 0)
	{
		return -1;
	}
		
	p = newCalcParams(opts);
	if(!p)
	{
		fprintf(stderr, "Cannot initialize CalcParams\n");
		return -1;
	}

	for(i = 0; i < opts->nFile; i++)
	{
		l = strlen(opts->files[i]);
		if(l > 6)
		{
			if(strcmp(opts->files[i]+l-6, ".input") == 0)
			{
				opts->files[i][l-6] = 0;
			}
			else if(strcmp(opts->files[i]+l-5, ".calc") == 0)
			{
				opts->files[i][l-5] = 0;
			}
		}
		if(opts->verbose > 0)
		{
			printf("Processing file %d/%d = %s\n",
				i+1, opts->nFile, opts->files[i]);
		}
		runfile(opts->files[i], opts, p);
	}
	deleteCalcParams(p);

	return 0;
}

int main(int argc, char **argv)
{
	CommandLineOptions *opts;

	opts = newCommandLineOptions(argc, argv);

	run(opts);

	deleteCommandLineOptions(opts);

	return 0;
}
