#!/bin/env python

from sys import argv
from string import strip, split

# Input file is SN table from AIPS prtab; BOX=1,2,4,12

data = open(argv[1]).readlines()

l = len(data)

N = 0
delays = ['0.0']*10

print '# Output from converdelay'
print '# Input file was: %s' % argv[1]

for i in range(l):
	s = split(strip(data[i]))
	if len(s) != 5:
		continue
	try:
		ant = int(s[3])
	except ValueError:
		continue
	if ant == 1:
		hms = split(s[1], ':')
		time = 56999.0 + int(hms[0])/24.0 + int(hms[1])/1440.0 + float(hms[2])/86400.0
		N = 0
		delays = ['0.0']*10
	if s[4] != 'INDE':
		N += 1 
		delays[ant-1] = s[4]
	if ant == 10 and N == 10:
		s = '%14.8f' % time
		for d in delays:
			s += ' ' + d
		print s
