#!/usr/bin/env python

from sys import argv, exit
from os import chdir, popen, system
from string import strip, split, find, lower, upper

program = 'difxsniff'
version = '1.1'
verdate = '20081229'
author  = 'Walter Brisken'

def run(pgm, args):
	print pgm
	p = popen(pgm, 'w')
	for a in args:
		p.write('%s\n' % a)
	p.close()

def usage():
	print '\n%s ver. %s   %s %s' % (program, version, verdate, author)
	print '\nA program to "sniff" FITS files made by DiFX\n'
	print 'Usage: ./difxsniff [options] <refants> <file1> [<file2> [...] ]'
	print '\nOptions can include:'
	print '  -h or --help : print this info and quit.'
	print 'each "file" is a FITS file made by difx2fits\n'

def sniff(filebases, refants, dir):

	if len(dir) > 0:
		system('mkdir -p ' + dir)

	# make apdfile
	apd = open(dir+'datafile.lis', 'w')
	first = 1
	for f in filebases:
		data = open(f+'.apd', 'r').readlines()
		if first:
			first = 0
			apd.write(data[0])
		for d in data[1:]:
			for r in refants:
				if find(d, r) > 0:
					apd.write(d)
					break
	apd.close()

	# make wtsfile
	wts = open(dir+'wtsfile.lis.sum', 'w')
	first = 1
	for f in filebases:
		data = open(f+'.wts', 'r').readlines()
		if first:
			first = 0
			wts.write(data[0])
		for d in data[1:]:
			wts.write(d)
	wts.close()

	# make acbandfile
	acb = open(dir+'acbandfile.lis', 'w')
	for f in filebases:
		data = open(f+'.acb', 'r').readlines()
		for d in data:
			acb.write(d)
	acb.close()

	# make xcbandfile
	xcb = open(dir+'xcbandfile.lis', 'w')
	for f in filebases:
		data = open(f+'.xcb', 'r').readlines()
		l = len(data)
		i = 0
		while(i < l):
			v = split(data[i])
			nif = int(v[-1])
			nch = int(v[-3])
			n = 2 + nif + nif*nch
			hasref = 0
			for r in refants:
				if find(data[i+2+nif], r):
					hasref += 1
			if hasref > 0:
				for j in range(i, i+n):
					xcb.write(data[j])
			i += n
	xcb.close()
	
	if len(dir) > 0:
		chdir(dir)

	run('plotapd', ['datafile.lis', 'apdfile.ps/vps', 'ALL', 'ALL'])
	run('plotwt',  ['wtsfile.lis.sum', 'wtsfile.ps/vps'])
	run('plotbp',  ['acbandfile.lis', 'acbandfile.ps/vps', ''])
	run('plotbp',  ['xcbandfile.lis', 'xcbandfile.ps/vps', ''])
	
files = []
refants = []
dir = 'sniffer/'

for a in argv[1:]:
	p = find(a, '.FITS')
	if p > 0:
		files.append(a[:p])
	elif find(a, '.') >= 0 and len(a) > 2:
		files.append(a)
	elif find(a, '/') > 0:
		dir = a
	elif a[0] == '-':
		if a == '-h' or a == '--help':
			usage()
			exit(0)
		else:
			print 'Error: unknown option : ' + a
	else:
		refants.append(upper(a))

if len(files) == 0:
	print 'Error: no input files provided.'
	exit(0)

if len(refants) == 0:
	print 'Error: no refants provided.'
	exit(0)

if dir[-1] != '/':
	dir += '/'

if len(refants) == 1:
	dir += refants[0] + '/'

sniff(files, refants, dir)

