#
# $Id: Makefile.am 4512 2026-05-10 21:48:06Z gbc $
#

if HAVE_DEVEL
SUBDIRS = . adump aedit alist average cohfit \
	fourfit fourmer fringex fplot search snratio @IFFYDIR@
else
SUBDIRS = . adump aedit alist average cohfit \
	fourfit fourmer fringex fplot search snratio
endif
DIST_SUBDIRS = $(SUBDIRS)

#
# eof
#
