struct type_2600 {
	short		record_id;		/*  */
	short		baseline_no;		/*  */
	char		baseline_id[2];		/*  */
	short		unused;			/*  */
	double		ap_accel;		/*  */
	double		ap_delay;		/*  */
	double		ap_rate;		/*  */
	double		pulse_accel;		/*  */
	double		u_1ghz;			/*  */
	double		v_1ghz;			/*  */
	double		u_rate;			/*  */
	double		v_rate;			/*  */
	double		ref_azimuth;		/*  */
	double		rem_azimuth;		/*  */
	double		ref_elev;		/*  */
	double		rem_elev;		/*  */
	double		gha;			/*  */
	double		prt_msec;		/*  */
	double		sid_rate;		/*  */
	double		source_baslin[3];	/*  */
	double		ha_rate;		/*  */
	double		ap_ref_clockrate;	/*  */
	double		ap_ref_syncerr;		/*  */
	double		ap_bas_syncerr;		/*  */
	double		ap_bas_clockrate;	/*  */
	double		ap_instr_delay;		/*  */
	double		two_pi;			/*  */
	double		u_obsfreq;		/*  */
	double		v_obsfreq;		/*  */
	double		u_obsfreq_rate;		/*  */
	double		v_obsfreq_rate;		/*  */
	double		pulse_phase;		/*  */
	double		pulse_freq;		/*  */
};
