struct type_2300 {
	short		record_id;		/*  */
	short		baseline_no;		/*  */
	char		baseline_id[2];		/*  */
	short		unused[5];		/*  */
	double		base_x_usec;		/*  */
	double		base_y_usec;		/*  */
	double		base_z_usec;		/*  */
	double		base_len_usec;		/*  */
	double		ra;			/*  */
	double		dec;			/*  */
	double		epoch;			/*  */
	double		ra_of_date;		/*  */
	double		dec_of_date;		/*  */
	double		pul_phas[4];		/*  */
	double		pul_epoch;		/*  */
	double		pul_disper;		/*  */
	double		unused2;		/*  */
	double		sample_rate;		/*  */
	double		ut1_utc;		/*  */
	double		two_pi;			/*  */
	double		ra_rate;		/*  */
	double		dec_rate;		/*  */
	double		gst_at_epoch;		/*  */
	double		gst_rate;		/*  */
	double		polar_motion[2];	/*  */
	double		ra_scale;		/*  */
	double		radec_partial[4];	/*  */
};
