struct type_2200 {
	short		record_id;		/*  */
	short		baseline_no;		/*  */
	char		baseline_id[2];		/*  */
	short		coord_type_ref;		/*  */
	short		coord_type_rem;		/*  */
	short		not_used[3];		/*  */
	double		ref_xlong;		/*  */
	double		rem_xlong;		/*  */
	double		ref_ylat;		/*  */
	double		rem_ylat;		/*  */
	double		ref_zelev;		/*  */
	double		rem_zelev;		/*  */
	double		ref_tsync;		/*  */
	double		rem_tsync;		/*  */
	double		ref_instr_delay;	/*  */
	double		rem_instr_delay;	/*  */
	double		ref_clock_rate;		/*  */
	double		rem_clock_rate;		/*  */
	double		ref_zen_atm;		/*  */
	double		rem_zen_atm;		/*  */
	double		ref_clock_epoch;	/*  */
	double		rem_clock_epoch;	/*  */
	double		ref_x_usec;		/*  */
	double		rem_x_usec;		/*  */
	double		ref_y_usec;		/*  */
	double		rem_y_usec;		/*  */
	double		ref_z_usec;		/*  */
	double		rem_z_usec;		/*  */
	double		vel_light;		/*  */
	double		spare[7];		/*  */
};
