#!/usr/bin/env python

from sys import argv, exit
from os import system

allmk5s = ['7','8','9','11','12','13','14','15','16','17','18','19','20','21','22','23','24']

program = 'mk5take'
version = '1.0'
verdate = '20080110'
author  = 'Walter Brisken'

def usage():
	print '\n%s ver. %s   %s %s' % (program, version, verdate, author)
	print '\nA program to kill the Mark5A program running on correlator mark5 unit(s)'
	print '\nUsage: %s [options] {<unit1> | all} [<unit2> [ ... ] ]' % (argv[0])
	print '\nOptions can include:'
	print '    -h or --help   print this help info\n'
	print 'unit1 ... unitN is the mark5 unit number.  "all" specifies all units.\n'
	print 'example:  mk5take 7 08 9 11 13'
	print 'example:  mk5take all\n'
	exit(0)

if len(argv) == 1:
	usage()
if argv[1] == '-h' or argv[1] == '--help':
	usage()

if argv[1] == 'all':
	list = allantennas
else:
	list = argv[1:]
for a in list:
	m5 = 'mark5fx%02d' % int(a)
	system('ssh %s EndM5' % m5)
