/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelButton.java
 *
 * Created on Jan 15, 2010, 12:08:31 PM
 */

package edu.nrao.difx.difxview;

/**
 *
 * @author mguerra
 */
public class JPanelButton extends javax.swing.JPanel {

    private boolean state = false;

    /** Creates new form JPanelButton */
    public JPanelButton() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jTogglePanelButton = new javax.swing.JToggleButton();

      jTogglePanelButton.setText("x");
      jTogglePanelButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTogglePanelButtonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jTogglePanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 16, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jTogglePanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 16, Short.MAX_VALUE)
      );
   }// </editor-fold>//GEN-END:initComponents

    private void jTogglePanelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTogglePanelButtonActionPerformed
    {//GEN-HEADEREND:event_jTogglePanelButtonActionPerformed
       state = !state;
       
    }//GEN-LAST:event_jTogglePanelButtonActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JToggleButton jTogglePanelButton;
   // End of variables declaration//GEN-END:variables

   public boolean getState()
   {
      return state;
   }
   
}
