/************************************************************************/
/*                                                                      */
/* Corrects the incoherent SNR values generated by average to the value */
/* they would have if the peak SNR was close to the incoherent          */
/* detection threshold.  Since the shape of the SNR/segtime curve is    */
/* a function of SNR, we must recalculate the SNRs for the marginal     */
/* detection case in order to fit the peak for the optimal segmentation */
/* time for weak sources.                                               */
/*                                                                      */
/*      Inputs:         codatum         1 baseline/scan, many segtimes  */
/*                      npt             Number of segtimes present      */
/*      Output:         codatum         duly normalized SNR values      */
/*                      return value    0=OK, else bad                  */
/*                                                                      */
/* codatum->navg[i] is the number of segments averaged together in      */
/* average when the -c flag is used                                     */
/*                                                                      */
/* Created January 10, 1996 by CJL                                      */
/* Hacked up April 26 2026 by GBC                                       */
/************************************************************************/
#include <math.h>
#include <stdio.h>
#include "mk4_util.h"
#include "cohfit.h"


int normalize_snr (cosumary *codatum, int npt)
    {
    int i;
    double snrseg[MAX_NSEGLEN], s, snra, n, s5, ratio, maxratio, maxsnra;

    maxratio = maxsnra = 0.0;
    for (i=0; i<npt; i++)
        {
                                        /* Calculate the SNR per segment */
                                        /* Remember peak SNRA */
        snra = codatum->snr[i];
        if (snra > maxsnra) maxsnra = snra;
        if ((n = codatum->navg[i]) == 0.0) 
            {
            msg ("Zero weight in input datum in normalize_snr()", 2);
            return (1);
            }
        snrseg[i] = sqrt ((2.0 / n) * (snra*snra + snra * sqrt(snra*snra + n)));
                                        /* Calculate segment SNR needed to */
                                        /* get SNRA of 5.0, and keep track of */
                                        /* max norm. ratio for all seglens */
        s5 = sqrt ((2.0 / n) * (25.0 + 5.0 * sqrt(25.0 + n)));
        ratio = snrseg[i] / s5;
        if (ratio > maxratio) maxratio = ratio;
        }
                                        /* Now recalculate the snra values, */
                                        /* based on peak SNRA of 5.0, but */
                                        /* renorm. back to original peak */
                                        /* SNRA value */
    msg("Adjusting SNR of data to threshold values.", 1);
    for (i=0; i<npt; i++)
        {
        float oldsnr = codatum->snr[i];
        n = codatum->navg[i];
        s = snrseg[i] / maxratio;
        codatum->snr[i] = (maxsnra/5.0) * (sqrt(n)/2.0) * s*s / sqrt(1.0 + s*s);
        msg("datum=%d   old_snr = %f  new_snr = %f", 1,
            oldsnr, codatum->snr[i]);
        }

    fflush(stdout);
    return (0);
    }
/*
 * eof vim:nospell
 */
