#!/bin/env python3

from sys import exit, stdout
import numpy as np
import argparse
from math import exp, log

program = 'apd2clock'
version = '0.1'
author = 'Walter Brisken <wbrisken@nrao.edu>'
verdate = '20260429'


# trims a floating point value
def stripZeros(s):
	if s.find('.') < 0:
		return s
	while s[-1] == '0':
		s = s[:-1]
	if s[-1] == '.':
		s = s[:-1]
	return s


# Provide:
# M: Matrix of baseline-based measurements (delay-like quantities)
# W: Matrix of baseline-based weights = 1/sigma
# R: index (0-based) of reference antenna
#
# Returns:
# Vector of antenna-based values
def SolvePhaseClosure(M, W, R):
	dim = len(M)
	Ek = np.zeros(dim)
	for k in range(dim):
		for j in range(dim):
			Ek[k] += 4.0*W[j][k]*W[j][k]*M[j][k]

	Ekl = npyy.zeros([dim, dim])
	for k in range(dim):
		for l in range(dim):
			Ekl[k][l] = 4.0*W[k][l]*W[k][l]
		for j in range(dim):
			Ekl[k][k] -= 4.0*W[k][j]*W[k][j]

	# constrain reference value to be zero
	Ek[R] = 0.0
	for j in range(dim):
		Ekl[j][R] = 0.0
		Ekl[R][j] = 0.0
	Ekl[R][R] = 1.0

	EklInv = np.linalg.inv(Ekl)

	return np.matmul(EklInv, Ek)

	

def addElement(arr, index, value):
	while len(arr) <= index:
		arr.append(None)
	arr[index] = value

class APDDelay:
	def __init__(self, line):
		self.parseAPDLine(line)

	def reset(self):
		self.mjd = 0.0
		self.ant1Id = 0
		self.ant1Name = ''
		self.ant2Id = 0
		self.ant2Name = ''
		self.sourceId = 0
		self.sourceName = ''
		self.delay = []		# (ns) indexed by channel Id
		self.weight = []	# indexed by channel Id arbitrary units; set equal to amp^2 here

	def parseAPDLine(self, line):
		self.reset()
		s = line.strip().split()
		# s[0] = integer MJD
		# s[1] = hours since UTC midnight
		# s[2] = source id (1-based index; change to 0-based on read)
		# s[3] = source name
		# s[4] = ant1 id (1-based index; change to 0-based on read)
		# s[5] = ant2 id (1-based index; change to 0-based on read)
		# s[6] = ant1 name
		# s[7] = ant2 name
		# s[8] = number of channels
		# remaining groups of 4 numbers: see "meas" above
		self.mjd = int(s[0]) + float(s[1])/24.0
		self.sourceId = int(s[2]) - 1
		self.sourceName = s[3]
		self.ant1Id = int(s[4]) - 1
		self.ant2Id = int(s[5]) - 1
		self.ant1Name = s[6]
		self.ant2Name = s[7]
		n = int(s[8])
		for i in range(n):
			self.delay.append(float(s[9 + 4*i])
			a = float(s[10 + 4*i])
			self.weight.append(a*a)

class APDDelays:
	def __init__(self, args):
		self.reset()
		if len(args) > 0:
			self.load(args)

	def reset(self):
		self.mjdStart = 0.0
		self.mjdEnd = 0.0
		self.antennaList = []
		self.sourceList = []
		self.delays = []
		self.obsCode = ''
		self.apdFile = ''
		self.nChan = 0

	def load(self, args):
		self.reset()
		apdFile = args[0]
		self.apdFile = apdFile
		data = open(apdFile).readlines()
		s = data[0].strip().split()
		if s[0] == 'obscode:':
			self.obscode = s[1]
		else:
			print('File format of %s is not recognized as a .apd file.' % apdFile)
			exit(0)
		for line in data[1:]
			delay = APDDelay(line)
			self.delays.append(delay)
			self.nChan = max(len(delay.delays), self.nChan)
			addElement(self.antennaList, delay.ant1Id, delay.ant1Name)
			addElement(self.antennaList, delay.ant2Id, delay.ant2Name)
			addElement(self.sourceList, delay.sourceId, delay.sourceName)
			if self.mjdStart < 1.0 or self.mjdStart > delay.mjd:
				self.mjdStart = delay.mjd
			if self.mjdEnd < delay.mjd:
				self.mjdEnd = delay.mjd

	def solveDelays(self, degree, chanList, refant, refTime = 0.0):
		if degree < 1 or degree > 2:
			print('degree=%d out of supported range.' % degree)
			exit(0)

		N = len(self.antennaList)	# Number of antennas 
		M = len(self.delays) 		# Number of measurements
		C = self.nChan			# Number of channels
		if refTime == 0.0:
			refTime = 0.5*(self.mjdStart + self.mjdEnd)

		# Weight and measurement arrays
		Wij = np.zeros([N, N])
		Xij = np.zeros([N, N])
		Yij = np.zeros([N, N])
		Tij = np.zeros([N, N])
		T2ij = np.zeros([N, N])
		for m in range(M):
			D = self.delays[m]
			t = M.mjd - refTime
			for c in range(C):
				if c in chanList:
					Wij[D.ant1Id][D.ant2Id] += D.weight[c]
					Wij[D.ant2Id][D.ant1Id] += D.weight[c]
					Xij[D.ant1Id][D.ant2Id] += D.delay[c]
					Xij[D.ant2Id][D.ant1Id] += D.delay[c]
					Yij[D.ant1Id][D.ant2Id] += t*D.delay[c]
					Yij[D.ant2Id][D.ant1Id] += t*D.delay[c]
					Tij[D.ant2Id][D.ant1Id] += t*D.weight[c]
					T2ij[D.ant1Id][D.ant2Id] += t*t*D.weight[c]
					T2ij[D.ant2Id][D.ant1Id] += t*t*D.weight[c]

		# Weight and measurement vectors
		Wi = np.zeros(N)
		Xi = np.zeros(N)
		Yi = np.zeros(N)
		Ti = np.zeros(N)
		T2i = np.zeros(N)
		for i in range(N):
			for j in range(N):
				Wi[i] += Wij[i][j]
				Xi[i] += Xij[i][j]
				Yi[i] += Yij[i][j]
				Ti[i] += Tij[i][j]
				T2i[i] += T2ij[i][j]

		# Vector and Matrix population
		V = np.zeros(2*N)
		M = np.zeros([2*N, 2*N])

		for i in range(N):
			V[i] = Xij[i][i] - Xi[i]
			for j in range(N):
				if i == j:
					M[i][j] = Wi[i][i] - Wij[i][i]
				else:
					M[i][j] = -Wij[i][j]
				if degree == 2:
					if i == j:
						M[N+i][N+i] = T2i[i] - T2ij[i][i]
						M[N+i][j] = M[i][N+j] = Ti[i] - Tij[i][j]
					else:
						M[N+i][N+j] = -T2ij[i][j]
						M[N+i][i] = M[i][N+i] = -Tij[i][j]
			if degree < 2:
				V[N+i] = 0.0
				M[N+i][n+i] = 1.0
			else:
				V[N+i] = Yij[i][i] - Yi[i]
				

		# Don't solve for refant values
		for i in range(2*N):
			M[i][refant] = M[refant][i] = 0.0
			M[i][N+refant] = M[N+refant][i] = 0.0
		M[refant][refant] = M[N+refant][N+refant] = 1.0
		V[refant] = V[N+refant] = 0.0

		return reftime, np.matmul(np.linalg.inv(M), V)


# Output is a dictionary of clock models indexed by antenna name
# Each value is an array with units of [ns/day^degree, ns/day^(degree-1), ..., ns]
# sign convention: FIXME
def process(times, chans, degree, reftime=0.0):
	mjds = []
	values = []	# indexed by time index
	for T in times:
		D = T[4]
		maxAnt = 0
		for d in D:
			if d[0] > maxAnt:
				maxAnt = d[0]
			if d[1] > maxAnt:
				maxAnt = d[1]
		ants = [None] * (maxAnt+1)
		for d in D:
			ants[d[0]] = d[2]
			ants[d[1]] = d[3]
		dim = len(ants)
		measurementIndex = 0    # Delay only
		try:
			R = int(refant) - 1	# zero based
		except:
			try:
				R = ants.index(refant)
			except:
				continue
		
		results = []
		for b in range(len(D[0][4])):
			if b in chans:
				M = np.zeros([dim, dim])
				W = np.zeros([dim, dim])
				try:
					for d in D:
						a1 = d[0]
						a2 = d[1]
						v = d[4][b][measurementIndex]
						w = d[4][b][1]
						M[a1][a2] = -v
						M[a2][a1] = v
						W[a1][a2] = w
						W[a2][a1] = w
					x = SolvePhaseClosure(M, W, R)
				except np.linalg.LinAlgError:
					continue
				results.append(x)
		if len(results) > 0:
			mjds.append(float(T[0]) + float(T[1])/24.0)
			values.append(results)	# values[timeIndex][channel][antenna]

	if reftime == 0:
		reftime = 0.5*(max(mjds) + min(mjds))
	T = np.array(mjds) - reftime
	clockUpdate = {}
	for a in range(len(ants)):	# FIXME: for now assume all times have same number of antennas
		D = np.zeros(len(mjds))
		for t in range(len(mjds)):
			n = 0
			for c in range(len(values[t])):
				n += 1
				D[t] += values[t][c][a]
			D[t] /= n
		M = np.polyfit(T, D, degree)
		clockUpdate[ants[a]] = M
	
	return reftime, clockUpdate


# chanFile looks like:

# obscode:  TR045B
# MJD 61135.39961227 2 1
# 1 7181.750 16.000 U R
# 2 7181.750 16.000 U L

def selectChans(chanFile, pol):
	maxRatio = 2.5
	try:
		data = open(chanFile).readlines()
	except:
		print('Could not read from %s' % chanFile)
		exit(0)
	IFs = []
	maxFreq = 0
	n = 0
	for d in data[2:]:
		s = d.strip().split()
		n += 1
		if n != int(s[0]):
			print('%s is badly formatted' % chanFile)
			exit(0)
		f = float(s[1])
		bw = float(s[2])
		sb = s[3]
		p = s[4]
		if sb == 'L':
			f -= 0.5*bw
		else:
			f += 0.5*bw
		IFs.append([f, p])
		if f > maxFreq and pol in [p, 'B']:
			maxFreq = f
	if maxFreq == 0:
		print('No channels match', IFs)
		exit(0)
	chans = []
	for i in range(len(IFs)):
		if IFs[i][0] > maxFreq / maxRatio and pol in [IFs[i][1], 'B']:
			chans.append(i)

	return chans

def tokenizeV2D(data):
	tokens = []
	specialChars = ['{', '=', '}', ',']
	for line in data:
		l = len(line)
		tokenStart = 0
		charType = 0	# 0 = unset, 1 = whitespace, 2 = other
		for i in range(l):
			if line[i] == '#':
				tokenStart = i
				break
			if line[i] in specialChars:
				if charType != 0:
					tokens.append(line[tokenStart:i])
				tokens.append(line[i])
				charType = 0
			elif line[i].isspace():
				if charType == 0:
					charType = 1
					tokenStart = i
				elif charType == 2:
					tokens.append(line[tokenStart:i])
					charType = 1
					tokenStart = i
			else:
				if charType == 0:
					charType = 2
					tokenStart = i
				elif charType == 1:
					tokens.append(line[tokenStart:i])
					charType = 2
					tokenStart = i
		tokens.append(line[tokenStart:])

	return tokens

def reassembleV2D(tokens, outputFile):
	if outputFile != None:
		output = open(outputFile, 'w')
	else:
		output = stdout
	for t in tokens:
		output.write(t)

def updateV2D(reftime, clockUpdate, inputFile, outputFile):
	parameters = ['clockEpoch', 'deltaClock', 'deltaClockRate']

	data = open(inputFile).readlines()
	tokens = tokenizeV2D(data)
	newTokens = []
	state = 0	# 0 = initial, 1 = found ANTENNA, 2 = fount antenna name, 3 = inside ANTENNA, 4 = looking for value
	data = {}
	for T in tokens:
		keep = True
		if state == 0 and T == 'ANTENNA':
			state = 1
		elif state == 1 and not T.isspace():
			ant = T
			if ant in clockUpdate:
				if len(clockUpdate[ant]) > 2:
					print('Error: v2d clock updates higher order than linear are not supported.')
					exit(0)
			values = {}
			data[ant] = values
			state = 2
		elif state == 2 and T == '{':
			state = 3
		elif state == 3 and T in parameters:
			param = T
			state = 4
			keep = False
		elif state == 4:
			if not T.isspace() and T != '=':
				values[param] = float(T)
				state = 3
			keep = False
		elif state == 3 and T == '}':
			state = 0
			# add back parameters as needed here
			if 'clockEpoch' in values:
				epoch = values['clockEpoch']
			else:
				epoch = reftime
			delta = rate = 0.0
			if 'deltaClock' in values:
				delta = values['deltaClock']
			if 'deltaClockRate' in values:
				rate = values['deltaClockRate']

			if ant in clockUpdate:
				delta += clockUpdate[ant][-1] / 1000.0
				if len(clockUpdate[ant]) > 1:
					rate += clockUpdate[ant][-2] / 1000.0
					delta += (epoch - reftime)*clockUpdate[ant][-2] / 1000.0
			
			if not newTokens[-1].isspace():
				newTokens.append(' ')
			if rate != 0 or 'clockEpoch' in values:
				newTokens += ['clockEpoch', '=', stripZeros('%13.7f' % epoch), ' ']
			if delta != 0:
				newTokens += ['deltaClock', '=', stripZeros('%8.6f' % delta), ' ']
			if rate != 0:
				newTokens += ['deltaClockRate', '=', stripZeros('%10.8f' % rate), ' ']
		if keep:
			newTokens.append(T)
	reassembleV2D(newTokens, outputFile)

def updateVex(clockUpdate, inputFile, outputFile):
	print('updating vex file not yet supported')

# ------

apdFile = None
refant = 0
pol = 'B'		# Both
refantSet = False
degree = 0		# 1 for linear, 2 for quadratic, ...
reftime = 0.0           # [mjd]
chans = []

parser = argparse.ArgumentParser('apd2clock', 'program to generate or update clock model based on an apd file', '')
parser.add_argument('apdFile', help='file to process')
parser.add_argument('-r', '--refant', help='specify a reference antenna, either by code or 1-based index')
parser.add_argument('-d', '--degree', type=int, help='clock model order; 0 or 1 is supported')
parser.add_argument('-i', '--input', help='input .vex or .v2d file; if not provided, just generate text output')
parser.add_argument('-o', '--output', help='filename for output data, otherwise send to stdout')
parser.add_argument('-p', '--polarization', help='polarization: R or L.  Will average both if not set')
parser.add_argument('-t', '--reftime', type=float, help='specify the reference time')
args = parser.parse_args()

apdFile = args.apdFile
if args.refant != None:
	refantSet = True
	refant = args.refant
if args.polarization != None:
	pol = args.polarization[0].upper()
if args.degree != None:
	degree = args.degree
if args.reftime != None:
	reftime = args.reftime

if len(chans) == 0:
	chanFile = apdFile[:-4] + '.channels'
	chans = selectChans(chanFile, pol)
	print('Chans: ', chans);

if apdFile == None:
	parser.print_help()
	exit(0)

obscode, times = loadAPD(apdFile)

reftime, clockUpdate = process(times, chans, degree, reftime)

if args.input == None:
	print('Ref time: %13.7f' % reftime)
	for key, value in clockUpdate.items():
		print('%s:' % key, value)
else:
	inputFile = args.input
	if inputFile[-4:] in ['.v2d', '.e2d']:
		updateV2D(reftime, clockUpdate, inputFile, args.output)
	elif inputFile[-4:] == '.vex':
		updateVex(clockUpdate, inputFile, args.output)
