#!/bin/env python3

from sys import exit, stdout
import numpy as np
import argparse
from math import exp, log

program = 'apd2clock2'
version = '0.2'
author = 'Walter Brisken <wbrisken@nrao.edu>'
verdate = '20260609'


# trims a floating point value
def stripZeros(s):
	if s.find('.') < 0:
		return s
	while s[-1] == '0':
		s = s[:-1]
	if s[-1] == '.':
		s = s[:-1]
	return s

def addElement(arr, index, value):
	while len(arr) <= index:
		arr.append(None)
	arr[index] = value

class APDDelay:
	def __init__(self, line):
		self.parseAPDLine(line)

	def reset(self):
		self.mjd = 0.0
		self.ant1Id = 0
		self.ant1Name = ''
		self.ant2Id = 0
		self.ant2Name = ''
		self.sourceId = 0
		self.sourceName = ''
		self.delay = []		# (ns) indexed by channel Id
		self.weight = []	# indexed by channel Id arbitrary units; set equal to amp^2 here

	def parseAPDLine(self, line):
		self.reset()
		s = line.strip().split()
		# s[0] = integer MJD
		# s[1] = hours since UTC midnight
		# s[2] = source id (1-based index; change to 0-based on read)
		# s[3] = source name
		# s[4] = ant1 id (1-based index; change to 0-based on read)
		# s[5] = ant2 id (1-based index; change to 0-based on read)
		# s[6] = ant1 name
		# s[7] = ant2 name
		# s[8] = number of channels
		# remaining groups of 4 numbers: see "meas" above
		self.mjd = int(s[0]) + float(s[1])/24.0
		self.sourceId = int(s[2]) - 1
		self.sourceName = s[3]
		self.ant1Id = int(s[4]) - 1
		self.ant2Id = int(s[5]) - 1
		self.ant1Name = s[6]
		self.ant2Name = s[7]
		n = int(s[8])
		for i in range(n):
			try:
				self.delay.append(float(s[9 + 4*i]))
				a = float(s[10 + 4*i])
				self.weight.append(a*a)
			except:
				print('Parse error, expecting floats: %s %s' % (s[9 + 4*i], s[10 + 4*i]))
				exit(0)

class APDDelays:
	def __init__(self, filename, unityWeights=False):
		self.reset()
		if len(filename) > 0:
			self.load(filename, unityWeights)

	def reset(self):
		self.mjdStart = 0.0
		self.mjdEnd = 0.0
		self.antennaList = []
		self.sourceList = []
		self.delays = []
		self.obsCode = ''
		self.apdFile = ''
		self.nChan = 0

	def nAnt(self):
		return len(self.antennaList)

	def getAntennaId(self, ant):
		if isinstance(ant, int):
			if ant < 0 or ant >= len(self.antennaList):
				print('refant = %d out of range' % ant)
				exit(0)
			return ant
		else:
			try:
				ant = int(ant)
				if ant < 0 or ant >= len(self.antennaList):
					print('refant = %d out of range' % ant)
					exit(0)
				return ant
			except:
				return self.antennaList.index(ant)

	def summarize(self):
		print('APDDelays')
		print('  obs: %s' % self.obsCode)
		print('  file: %s' % self.apdFile)
		print('  antennas: ', self.antennaList)
		print('  antennas: %s' % ' '.join(self.antennaList))
		#print('  sources: %s' % ' '.join(self.sourceList))
		print('  n delay: %d\n' % len(self.delays))

	def load(self, apdFile, unityWeights=False):
		self.reset()
		self.apdFile = apdFile
		nanRows = 0
		data = open(apdFile).readlines()
		s = data[0].strip().split()
		if s[0] == 'obscode:':
			self.obsCode = s[1]
		else:
			print('File format of %s is not recognized as a .apd file.' % apdFile)
			exit(0)
		for line in data[1:]:
			if line.lower().find('nan') >= 0:
				nanRows += 1
			else:
				delay = APDDelay(line)
				if unityWeights:
					delay.weight = [1.0]*len(delay.weight)
				self.delays.append(delay)
				self.nChan = max(len(delay.delay), self.nChan)
				addElement(self.antennaList, delay.ant1Id, delay.ant1Name)
				addElement(self.antennaList, delay.ant2Id, delay.ant2Name)
				addElement(self.sourceList, delay.sourceId, delay.sourceName)
				if self.mjdStart < 1.0 or self.mjdStart > delay.mjd:
					self.mjdStart = delay.mjd
				if self.mjdEnd < delay.mjd:
					self.mjdEnd = delay.mjd
		L = [x for x in self.antennaList if x is not None]
		if len(L) < len(self.antennaList):
			print('Shortening antenna list from ', self.antennaList, ' to ', L)
			antMap = []
			j = 0
			for a in self.antennaList:
				antMap.append(j)
				if a != None:
					j += 1
			self.antennaList = L
			for D in self.delays:
				D.ant1Id = antMap[D.ant1Id]
				D.ant2Id = antMap[D.ant2Id]
		if nanRows > 0:
			print('Note: %d row(s) discarded because of NaNs' % nanRows)

	def medianWeights(self, chanList):
		nChan=len(chanList)
		N = len(self.delays)
		W = [[] for c in chanList]
		S = [0.0]*nChan
		median = []
		for D in self.delays:
			for c in range(nChan):
				S[c] += D.weight[chanList[c]]
				W[c].append(D.weight[chanList[c]])
		mean = [x/N for x in S]
		for c in range(nChan):
			W[c].sort()
			median.append(W[c][N//2])
		for c in range(nChan):
			print('chan[%d] : min=%e mean=%e median=%e max=%e' % (chanList[c], W[c][0], mean[c], median[c], W[c][N-1]))

	def solveDelays(self, degree, chanList, refant, referenceTime = 0.0):
		if degree < 0 or degree > 1:
			print('degree=%d out of supported range.' % degree)
			exit(0)

		N = len(self.antennaList)	# Number of antennas 
		M = len(self.delays) 		# Number of measurements
		C = self.nChan			# Number of channels
		if referenceTime == 0.0:
			referenceTime = 0.5*(self.mjdStart + self.mjdEnd)

		# Weight and measurement arrays
		Wij = np.zeros([N, N])
		Xij = np.zeros([N, N])
		Yij = np.zeros([N, N])
		Tij = np.zeros([N, N])
		T2ij = np.zeros([N, N])
		for m in range(M):
			D = self.delays[m]
			t = D.mjd - referenceTime
			for c in range(C):
				if c in chanList:
					Wij[D.ant1Id][D.ant2Id] += D.weight[c]
					Wij[D.ant2Id][D.ant1Id] += D.weight[c]
					Tij[D.ant1Id][D.ant2Id] += t*D.weight[c]
					Tij[D.ant2Id][D.ant1Id] += t*D.weight[c]
					T2ij[D.ant1Id][D.ant2Id] += t*t*D.weight[c]
					T2ij[D.ant2Id][D.ant1Id] += t*t*D.weight[c]
					Xij[D.ant1Id][D.ant2Id] += D.delay[c]*D.weight[c]
					Xij[D.ant2Id][D.ant1Id] -= D.delay[c]*D.weight[c]
					Yij[D.ant1Id][D.ant2Id] += t*D.delay[c]*D.weight[c]
					Yij[D.ant2Id][D.ant1Id] -= t*D.delay[c]*D.weight[c]

		# Weight and measurement vectors
		Wi = np.zeros(N)
		Xi = np.zeros(N)
		Yi = np.zeros(N)
		Ti = np.zeros(N)
		T2i = np.zeros(N)
		for i in range(N):
			for j in range(N):
				Wi[i] += Wij[i][j]
				Xi[i] += Xij[i][j]
				Yi[i] += Yij[i][j]
				Ti[i] += Tij[i][j]
				T2i[i] += T2ij[i][j]

		# Vector and Matrix population
		VV = np.zeros(2*N)
		MM = np.zeros([2*N, 2*N])

		for i in range(N):
			VV[i] = -Xi[i]
			for j in range(N):
				if i == j:
					MM[i][j] = Wi[i] - Wij[i][i]
				else:
					MM[i][j] = -Wij[i][j]
				if degree  > 0:
					if i == j:
						MM[N+i][N+i] = T2i[i] - T2ij[i][i]
						MM[N+i][i] = MM[i][N+i] = Ti[i] - Tij[i][i]
					else:
						MM[N+i][N+j] = -T2ij[i][j]
						MM[N+i][j] = MM[i][N+j] = -Tij[i][j]
			if degree == 0:
				MM[N+i][N+i] = 1.0
			else:
				VV[N+i] = -Yi[i]
				
		# constrain refant values
		refantWeight = Wij.mean()	# just need this to be right order of magnitude
		refantDelay = 0.0
		refantRate = 0.0
		MM[refant][refant] += refantWeight
		VV[refant] += refantWeight*refantDelay
		if degree > 0:
			MM[N+refant][N+refant] += refantWeight
			VV[N+refant] += refantWeight*refantRate

		return referenceTime, np.matmul(np.linalg.inv(MM), VV)


# chanFile looks like:

# obscode:  TR045B
# MJD 61135.39961227 2 1
# 1 7181.750 16.000 U R
# 2 7181.750 16.000 U L

def selectChans(chanFile, pol):
	maxRatio = 2.5
	try:
		data = open(chanFile).readlines()
	except:
		print('Could not read from %s' % chanFile)
		exit(0)
	IFs = []
	maxFreq = 0
	n = 0
	for d in data[2:]:
		s = d.strip().split()
		n += 1
		if n != int(s[0]):
			print('%s is badly formatted' % chanFile)
			exit(0)
		f = float(s[1])
		bw = float(s[2])
		sb = s[3]
		p = s[4]
		if sb == 'L':
			f -= 0.5*bw
		else:
			f += 0.5*bw
		IFs.append([f, p])
		if f > maxFreq and pol in [p, 'B']:
			maxFreq = f
	if maxFreq == 0:
		print('No channels match', IFs)
		exit(0)
	chans = []
	for i in range(len(IFs)):
		if IFs[i][0] > maxFreq / maxRatio and pol in [IFs[i][1], 'B']:
			chans.append(i)

	return chans

def tokenizeV2D(data):
	tokens = []
	specialChars = ['{', '=', '}', ',']
	for line in data:
		l = len(line)
		tokenStart = 0
		charType = 0	# 0 = unset, 1 = whitespace, 2 = other
		for i in range(l):
			if line[i] == '#':
				tokenStart = i
				break
			if line[i] in specialChars:
				if charType != 0:
					tokens.append(line[tokenStart:i])
				tokens.append(line[i])
				charType = 0
			elif line[i].isspace():
				if charType == 0:
					charType = 1
					tokenStart = i
				elif charType == 2:
					tokens.append(line[tokenStart:i])
					charType = 1
					tokenStart = i
			else:
				if charType == 0:
					charType = 2
					tokenStart = i
				elif charType == 1:
					tokens.append(line[tokenStart:i])
					charType = 2
					tokenStart = i
		tokens.append(line[tokenStart:])

	return tokens

def reassembleV2D(tokens, outputFile):
	if outputFile != None:
		output = open(outputFile, 'w')
	else:
		output = stdout
	for t in tokens:
		output.write(t)

def updateV2D(referenceTime, clockUpdate, inputFile, outputFile):
	parameters = ['clockEpoch', 'deltaClock', 'deltaClockRate']

	data = open(inputFile).readlines()
	tokens = tokenizeV2D(data)
	newTokens = []
	state = 0	# 0 = initial, 1 = found ANTENNA, 2 = fount antenna name, 3 = inside ANTENNA, 4 = looking for value
	data = {}
	for T in tokens:
		keep = True
		if state == 0 and T == 'ANTENNA':
			state = 1
		elif state == 1 and not T.isspace():
			ant = T
			if ant in clockUpdate:
				if len(clockUpdate[ant]) > 2:
					print('Error: v2d clock updates higher order than linear are not supported.')
					exit(0)
			values = {}
			data[ant] = values
			state = 2
		elif state == 2 and T == '{':
			state = 3
		elif state == 3 and T in parameters:
			param = T
			state = 4
			keep = False
		elif state == 4:
			if not T.isspace() and T != '=':
				values[param] = float(T)
				state = 3
			keep = False
		elif state == 3 and T == '}':
			state = 0
			# add back parameters as needed here
			if 'clockEpoch' in values:
				epoch = values['clockEpoch']
			else:
				epoch = referenceTime
			delta = rate = 0.0
			if 'deltaClock' in values:
				delta = values['deltaClock']
			if 'deltaClockRate' in values:
				rate = values['deltaClockRate']

			if ant in clockUpdate:
				delta += clockUpdate[ant][0] / 1000.0
				if len(clockUpdate[ant]) > 1:
					rate += clockUpdate[ant][1] / 1000.0
					delta += (epoch - referenceTime)*clockUpdate[ant][1] / 1000.0

			if not newTokens[-1].isspace():
				newTokens.append(' ')
			if rate != 0 or 'clockEpoch' in values:
				newTokens += ['clockEpoch', '=', stripZeros('%13.7f' % epoch), ' ']
			if delta != 0:
				newTokens += ['deltaClock', '=', stripZeros('%8.6f' % delta), ' ']
			if rate != 0:
				newTokens += ['deltaClockRate', '=', stripZeros('%10.8f' % rate), ' ']
		if keep:
			newTokens.append(T)
	reassembleV2D(newTokens, outputFile)

def updateVex(clockUpdate, inputFile, outputFile):
	print('updating vex file not yet supported')

# ------

apdFile = None
refant = 0
pol = 'B'		# Both
refantSet = False
degree = 0		# 1 for linear, 2 for quadratic, ...
referenceTime = 0.0           # [mjd]
chans = []
unityWeights = False

parser = argparse.ArgumentParser('apd2clock', 'program to generate or update clock model based on an apd file', '')
parser.add_argument('apdFile', help='file to process')
parser.add_argument('-r', '--refant', help='specify a reference antenna, either by code or 1-based index')
parser.add_argument('-d', '--degree', type=int, help='clock model order; 0 or 1 is supported')
parser.add_argument('-i', '--input', help='input .vex or .v2d file; if not provided, just generate text output')
parser.add_argument('-o', '--output', help='filename for output data, otherwise send to stdout')
parser.add_argument('-p', '--polarization', help='polarization: R or L.  Will average both if not set')
parser.add_argument('-t', '--referenceTime', type=float, help='specify the reference time')
parser.add_argument('-c', '--channels', type=str, help='explicitly list channeld IDs to use (0-based)')
parser.add_argument('-u', '--unityWeights', action='store_true')
args = parser.parse_args()

apdFile = args.apdFile
if args.refant != None:
	refantSet = True
	refant = args.refant
if args.polarization != None:
	pol = args.polarization[0].upper()
if args.degree != None:
	degree = args.degree
if args.referenceTime != None:
	referenceTime = args.referenceTime
if args.channels != None:
	chans = [int(x) for x in args.channels.split(',')]
unityWeights = args.unityWeights

if len(chans) == 0:
	chanFile = apdFile[:-4] + '.channels'
	chans = selectChans(chanFile, pol)
	print('Chans: ', chans);

if apdFile == None:
	parser.print_help()
	exit(0)

apd = APDDelays(apdFile, unityWeights)
apd.summarize()
refant = apd.getAntennaId(refant)

apd.medianWeights(chans)

referenceTime, deltaClock = apd.solveDelays(degree, chans, refant, referenceTime)
print('Reference time = %14.8f' % referenceTime)
print('Delta clock = ', deltaClock)

if args.input != None:
	inputFile = args.input
	nAnt = apd.nAnt()

	# reformat the clock update
	clockUpdate = {}
	for i in range(nAnt):
		a = apd.antennaList[i]
		clockUpdate[a] = np.zeros(degree+1)
		for j in range(degree + 1):
			clockUpdate[a][j] = deltaClock[i + nAnt*j]

	print('clockUpdate=', clockUpdate)

	if inputFile[-4:] in ['.v2d', '.e2d']:
		print()
		updateV2D(referenceTime, clockUpdate, inputFile, args.output)
	elif inputFile[-4:] == '.vex':
		updateVex(deltaClock, inputFile, args.output)
